### ISSUE TITLE
Unable to access jarfile VertigoBoostingPanel.jar

### ISSUE THREAD

**Issue by kokotko1337** [SamHoque/Vertigo-Boosting-Panel#1]
after i execute start.bat ... any idea ? 

Error: Unable to access jarfile VertigoBoostingPanel.jar
Press any key to continue . . .

**Comment by frapii** [comment]
same issue :C

**Comment by 7-teen** [comment]
> same issue :C



> after i execute start.bat ... any idea ?
> 
> Error: Unable to access jarfile VertigoBoostingPanel.jar
> Press any key to continue . . .

Guys you are downloading the source code where there is no such jar file.

Download the top 3 files from: https://github.com/SamHoque/Vertigo-Boosting-Panel/releases/tag/1.0.0
Put then into a folder and run start (You need java for this to work)
I hope this helps.

**Comment by muratcansimsek** [comment]
> > same issue :C
> 
> > after i execute start.bat ... any idea ?
> > Error: Unable to access jarfile VertigoBoostingPanel.jar
> > Press any key to continue . . .
> 
> Guys you are downloading the source code where there is no such jar file.
> 
> Download the top 3 files from: https://github.com/SamHoque/Vertigo-Boosting-Panel/releases/tag/1.0.0
> Put then into a folder and run start (You need java for this to work)
> I hope this helps.


it's given another error
https://i.imgur.com/7yxjGX8.png


edit: problem solved cuz of im an idiot, after installing java solved my problem.
