### ISSUE TITLE
I can't find the same server.

### ISSUE THREAD

**Issue by muratcansimsek** [SamHoque/Vertigo-Boosting-Panel#4]
I even tried a route tool, but still can't find it. Wingman. (others blocked and selected honkong servers mm 350)

Any solution?

team1
1x LEM prime
1x non prime no rank

team2
1x non prime no rank
1x non prime no rank

**Comment by StrPlayer** [comment]
put a lem on the other team

**Comment by muratcansimsek** [comment]
after installing new mm picker problem is fixed. //closed
