### ISSUE TITLE
Crash CS:GO and Error "Invalid app configuration"

### ISSUE THREAD

**Issue by z0g1** [SamHoque/Vertigo-Boosting-Panel#6]
When you start cs go in the process, it appears for 10-20 seconds and seems to start, but after that the process freezes and just crashes.
I also want to ask how you can fix the "Invalid app configuration" error?

**Comment by muratcansimsek** [comment]
same issue

**Comment by muratcansimsek** [comment]
**closed without an answer again** feelsbadman
